# See: https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper

preload = ~/images/wallpapers/yuuki.png

wallpaper {
    monitor = HDMI-A-1
    path = ~/images/wallpapers/yuuki.png
    # path = ~/images/kamchoolya
    # timeout = 1
}

wallpaper {
    monitor = DP-3
    path = ~/images/wallpapers/yuuki.png
}

splash = false
