# See: https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper

wallpaper {
    monitor = HDMI-A-1
    path = ~/images/wallpapers/yuuki.png
    # path = ~/images/kamchoolya
    # timeout = 1
}
splash = false
