# Qt6 platform theme when QT_QPA_PLATFORMTHEME=hyprqt6engine
# See: https://wiki.hypr.land/Hypr-Ecosystem/hyprqt6engine/

theme {
    color_scheme = /usr/share/color-schemes/Sweet.colors
    icon_theme = Sweet-Rainbow
    style = kvantum-dark
    font = NotoSans Nerd Font
    font_size = 14
    font_fixed = CaskaydiaCove Nerd Font Mono
    font_fixed_size = 14
}
