# Shared toolkit theme (hyprlauncher, hyprshutdown UI, etc.)
# See: https://wiki.hypr.land/Hypr-Ecosystem/hyprtoolkit/

# #161925ff
background = 0xFF161925
# #282c34ff
base = 0xFF282C34
# #1f2335ff
alternate_base = 0xFF1f2335
# #c3c7c8ff
text = 0xFFc3c7c8
# #dcdfe4ff
bright_text = 0xFFdcdfe4
# #c74dedff
accent = 0xFFc74ded
# #ed254eff
accent_secondary = 0xFFed254e

h1_size = 22
h2_size = 17
h3_size = 14
font_size = 14
small_font_size = 12

font_family = NotoSans Nerd Font
font_family_monospace = CaskaydiaCove Nerd Font Mono
icon_theme = Sweet-Rainbow

rounding_large = 10
rounding_small = 5
