# Window, workspace and layer rules

# To check open windows's ids runL
# hyprctl clients

# Window rules, see:
# - https://wiki.hyprland.org/Configuring/Window-Rules/
# - https://wiki.hyprland.org/Configuring/Dispatchers


# Add opacity to windows
windowrule {
  name = windowrule-steam
  opacity = 0.80 0.80
  match:class = ^(steam)$
}

windowrule {
  name = windowrule-steam-webhelper
  opacity = 0.80 0.80
  match:class = ^(steamwebhelper)$
}

windowrule {
  name = windowrule-dolphin
  opacity = 0.80 0.80
  match:class = ^(org.kde.dolphin)$
}

windowrule {
  name = windowrule-xdg-desktop-portals
  opacity = 0.80 0.80
  match:class = ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
}

windowrule {
  name = windowrule-qt5ct
  opacity = 0.80 0.80
  match:class = ^(qt5ct)$
}

windowrule {
  name = windowrule-qt6ct
  opacity = 0.80 0.80
  match:class = ^(qt6ct)$
}

windowrule {
  name = windowrule-kvantum
  opacity = 0.80 0.80
  match:class = ^(kvantummanager)$
}

windowrule {
  name = windowrule-obs
  opacity = 0.80 0.80
  match:class = ^(com.obsproject.Studio)$
}

windowrule {
  name = windowrule-discord
  opacity = 0.80 0.80
  match:class = ^(discord)$
}

windowrule {
  name = windowrule-yad
  opacity = 0.80 0.80
  float = on
  match:class = ^(yad)$
}

windowrule {
  name = windowrule-pavuk
  opacity = 0.80 0.70
  float = on
  match:class = ^(pavucontrol)$
}

windowrule {
  name = windowrule-blueman
  opacity = 0.80 0.70
  float = on
  match:class = ^(blueman-manager)$
}

windowrule {
  name = windowrule-networkmanager
  opacity = 0.80 0.70
  float = on
  match:class = ^(nm-applet)$
}

windowrule {
  name = windowrule-nm-connecition-editor
  opacity = 0.80 0.70
  float = on
  match:class = ^(nm-connection-editor)$
}

windowrule {
  name = windowrule-polkit
  opacity = 0.80 0.70
  float = on
  match:class = ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
}


# ignore opactity rules for all windows on 9 workspace
windowrule {
  name = windowrule-ignore-opacity
  opacity = 1.00 override 1.00 override
  match:workspace = 9
}

# Make floating by default
windowrule {
  name = windowrule-floating-dolphin-progress
  float = on
  match:class = ^(org.kde.dolphin)$
  match:title = ^(Progress Dialog — Dolphin)$
}

windowrule {
  name = windowrule-floating-dolphin-copying
  float = on
  match:class = ^(org.kde.dolphin)$
  match:title = ^(Copying — Dolphin)$
}

windowrule {
  name = windowrule-floating-portals
  float = on
  match:class = ^(org.freedesktop.impl.portal.desktop.kde|xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
}

windowrule {
  name = windowrule-floating-pip
  float = on
  match:title = ^(Picture-in-Picture)$
}

windowrule {
  name = windowrule-floating-save-dialog
  float = on
  match:title = ^(Save File)$
}

windowrule {
  name = windowrule-floating-rename
  float = on
  match:title = ^(Enter name of file.*)
}

windowrule {
  name = windowrule-floating-sabe-image
  float = on
  match:title = ^(Save Image)$
}

windowrule {
  name = windowrule-floating-open-dialog
  float = on
  match:title = ^(Open File)$
}

windowrule {
  name = windowrule-floating-firefox
  float = on
  match:class = ^(firefox)$
  match:title = ^(Library)$
}

windowrule {
  name = windowrule-floating-ark
  float = on
  match:class = ^(org.kde.ark)$
}



# Layer rules, see:
# - https://wiki.hyprland.org/Configuring/Window-Rules/#layer-rules


layerrule {
  name = layerrule-notifications
  blur = on
  ignore_alpha = 0
  match:namespace = notifications
}

layerrule {
  name = layerrule-logout
  blur = on
  match:namespace = logout_dialog
}



# Workspace rules, see:
# - https://wiki.hyprland.org/Configuring/Workspace-Rules/
