# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[background]
# Path to the background image
path = "/usr/share/backgrounds/greet.png"

# How the background image covers the screen if the aspect ratio doesn't match
# Available values: "Fill", "Contain", "Cover", "ScaleDown"
# Refer to: https://docs.gtk.org/gtk4/enum.ContentFit.html
# NOTE: This is ignored if ReGreet isn't compiled with GTK v4.8 support.
fit = "Fill"

# The entries defined in this section will be passed to the session as environment variables when it is started
[env]
# GTK wayland backend: https://wiki.archlinux.org/title/Wayland#GTK
GDK_BACKEND = "wayland"

# Qt HidhDPI settings: https://doc.qt.io/qt-6/highdpi.html
# QT_AUTO_SCREEN_SCALE_FACTOR=1
# QT_SCALE_FACTOR=1

# Qt wayland backend: https://wiki.archlinux.org/title/Wayland#Qt
QT_QPA_PLATFORM = "wayland;xcb"

# KDE File Picker by default: https://bbs.archlinux.org/viewtopic.php?id=253132
GTK_USE_PORTAL = "1"

# Firefox wayland backend: https://wiki.archlinux.org/title/Firefox#Wayland
MOZ_ENABLE_WAYLAND = "1"

# Nvidia-specific settings: https://wiki.archlinux.org/title/Wayland#Requirements
# GBM_BACKEND=nvidia-drm
# __GLX_VENDOR_LIBRARY_NAME=nvidia

# Force session to run on Nvidia GPU on laptops with
# prime render offload, see: https://wiki.archlinux.org/title/PRIME#Configure_applications_to_render_using_GPU
# __NV_PRIME_RENDER_OFFLOAD=1
# Additional prime settings: https://wiki.archlinux.org/title/PRIME#Wayland-specific_configuration
# __VK_LAYER_NV_optimus=NVIDIA_only

# SDL2 wayland backend: https://wiki.archlinux.org/title/Wayland#SDL2
SDL_VIDEODRIVER = "wayland,x11"

# Try to set electron backend: https://wiki.archlinux.org/title/Wayland#Electron
ELECTRON_OZONE_PLATFORM_HINT = "wayland"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Sweet-cursors"

# Font name and size
font_name = "NotoSans Nerd Font 16"

# Icon theme name
icon_theme_name = "Sweet-Rainbow"

# GTK theme name
theme_name = "Sweet"

[commands]
# The command used to reboot the system
reboot = [ "systemctl", "reboot" ]

# The command used to shut down the system
poweroff = [ "systemctl", "poweroff" ]
