monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Audeze_LLC_Audeze_Maxwell.*"
      }
      {
        node.name = "~alsa_input.usb-Audeze_LLC_Audeze_Maxwell.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]

