clipboard_cmd = "cliphist.sh"

[modules]
left = [ "SystemInfo", "Workspaces", "MediaPlayer" ]
center = [ "WindowTitle" ]
right = [ [ "Clipboard", "KeyboardLayout" ], [ "Tray", "Clock", "Privacy", "Settings" ] ]

[workspaces]
visibility_mode = "MonitorSpecific"

[keyboard_layout.labels]
"English (US)" = "en-US"
"Russian" = "ru-RU"

[clock]
format = "%R %d.%m.%Y"

[settings]
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[appearance]
font_name = "NotoSans Nerd Font"
background_color = "#161925"
primary_color = "#00c1e4"
text_color = "#c74ded"
workspace_colors = [ "#00c1e4" ]

[appearance.menu]
opacity = 0.7
