[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black = "#697388"
red = "#ed254e"
green = "#71f79f"
yellow = "#f9dc5c"
blue = "#7cb7ff"
magenta = "#c74ded"
cyan = "#00c1e4"
white = "#dcdfe4"

[colors.bright]
white = "#ffffff"
