# Kickoff default config

# Characters shown in front of the query.
prompt = ''

# space between window border and the content in pixel
padding = 100

fonts = [
    'Noto Sans Mono',
] # list of otf or ttf fonts. later elements work as fallback
font_size = 32.0

[search]
show_hidden_files = true

[history]
decrease_interval = 48 # interval to decrease the number of launches in hours

[colors]
# color format: rgb or rgba, if transparency is desired
background = '#000000bb'
prompt = '#f9dc5cff'
text = '#c3c7c8ff' 
text_query = '#00c1e4ff'
text_selected = '#bd93f9ff'

[keybindings]
# keybindings syntax: ctrl/shift/alt/logo as modifiers and a key joined by '+' signs
# A list of available keys can be found here: https://docs.rs/crate/x11-keysymdef/0.2.0/source/src/keysym.json
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
