# See https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

# [env]
# ZDOTDIR = "/home/gigas/.config/zsh/"

[window]
opacity = 0.3
blur = true
startup_mode = "Maximized"

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 14.0

[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/themes/Sweet.toml"]

[terminal]

shell = "nu"
